FROM almalinux:9
RUN dnf install nginx -y 
CMD ["nginx","-g","daemon off;"]

# #if the images is avalible in the local repo then we can rewrite the above as 
# From run:1.0 
# CMD ["nginx","-g","daemon off;"]
